### ISSUE TITLE
bug/feat: No Dynamic Resizing 

### ISSUE THREAD

**Issue by arunmathaisk** [18alantom/fex#2]
![image](https://github.com/18alantom/fex/assets/61804369/885401ae-b9f4-481d-a869-6e2ec44257fc)

**Comment by arunmathaisk** [comment]
Not sure if it is a shell specific issue. I am on bash fyi

**Comment by 18alantom** [comment]
Should be handled in https://github.com/18alantom/fex/commit/2610eccb544c4e6df8383d554a192ff24395346b.

(adjusts viewport on input after resizing)
